[project]
name = "oakestra"
version = "0.0.0"
requires-python = ">=3.10.13"

[tool.uv.workspace]
members = [
    "cluster_orchestrator/cluster-manager",
    "root_orchestrator/system-manager-python",
    "libraries/*",
]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
    ".github/*",
    "**/proto",
]
[tool.ruff.lint]
extend-select = [
    "TD",  # todos
    "I",  # isort
]
ignore = [
    "TD003",  # missing TODO link: ignored because we don't require adding tickets to TODOs
    "TD002",  # missing TODO author: ignored because we don't specify authors for all TODOs currently
    "BLE001", # blind "Exception" catch: ignored because we currently rely on this a lot
    "EXE002", # executable script without shebang: ignored because we don't really expect it to be executed directly

]
