[project]
name = "oakestra"
version = "0.0.0"
requires-python = ">=3.10.13"

[tool.uv.workspace]
members = [
    "cluster_orchestrator/cluster-manager",
    "libraries/*",
]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
    ".github/*",
    "**/proto",
]
[tool.ruff.lint]
extend-select = [
    "TD",  # todos
    "I",  # isort
]
ignore = [
    "TD003",  # missing-todo-link. Ignored because we don't require adding tickets to TODOs
]
